Question.create([
                  {question: "What is your biggest strength?", category: "general"},
                  {question: "What is your biggest weakness?", category: "general"},
                  {question: "Why do you want this job?", category: "general"},
                  {question: "Why are you leaving your present job?", category: "general"},
                  {question: "When were you most satisfied in your job?", category: "general"},
                  {question: "What did you like least about your last job?", category: "general"},
                  {question: "What can you do for us that other candidates can't?", category: "general"},
                  {question: "Can you describe a time when your work was criticized?", category: "general"},
                  {question: "Give me an example of a time that you felt you went above and beyond the call of duty at work.", category: "general"},
                  {question: "What was the last project you headed up, and what was its outcome?", category: "general"},
                  {question: "Have you ever been on a team where someone was not pulling their own weight? How did you handle it?", category: "general"},
                  {question: "Where would you like to be in your career five years from now?", category: "general"},
                  {question: "What attracted you to this company?", category: "general"},
                  {question: "Why should we hire you?", category: "general"},
                  {question: "What were the responsibilities of your last position?", category: "general"},
                  {question: "Do you have any questions for me?", category: "general"},
                  {question: "Tell me about a time when you had to give someone difficult feedback. How did you handle it?", category: "general"},
                  {question: "What is your greatest failure, and what did you learn from it?", category: "general"},
                  {question: "What irritates you about other people, and how do you deal with it?", category: "general"},
                  {question: "If I were your supervisor and asked you to do something that you disagreed with, what would you do?", category: "general"},
                  {question: "What's the most difficult decision you've made in the last two years and how did you come to that decision?", category: "general"},
                  {question: "Describe how you would handle a situation if you were required to finish multiple tasks by the end of the day, and there was no conceivable way that you could finish them.", category: "general"},
                  {question: "What salary are you seeking?", category: "general"},
                  {question: "If I were to give you this salary you requested but let you write your job description for the next year, what would it say?", category: "general"},
                  {question: "How do you want to improve yourself in the next year?", category: "general"},
                  {question: "What kind of goals would you have in mind if you got this job?", category: "general"},
                  {question: "If I were to ask your last supervisor to provide you additional training or exposure, what would she suggest?", category: "general"},
                  {question: "What do you see yourself doing within the first 30 days of this job?", category: "general"},
                  {question: "If selected for this position, can you describe your strategy for the first 90 days?", category: "general"},
                  {question: "What would be your ideal working environment?", category: "general"},
                  {question: "What techniques and tools do you use to keep yourself organized?", category: "general"},
                  {question: "Tell me about your proudest achievement.", category: "general"},
                  {question: "Who was your favorite manager and why?", category: "general"},
                  {question: "What do you think of your previous boss?", category: "general"},
                  {question: "What do you like to do for fun?", category: "general"},
                  {question: "What are three positive things your last boss would say about you?", category: "general"},
                  {question: "What negative thing would your last boss say about you?", category: "general"},
                  {question: "What three character traits would your friends use to describe you?", category: "general"},
                  {question: "If you were interviewing someone for this position, what traits would you look for?", category: "general"},
                  {question: "Who has impacted you most in your career and how?", category: "general"},
                  {question: "What is your greatest fear?", category: "general"},
                  {question: "What is your biggest regret and why?", category: "general"},
                  {question: "What's the most important thing you learned in school?", category: "general"},
                  {question: "What will you miss about your present/last job?", category: "general"},
                  {question: "What are the qualities of a good leader? A bad leader?", category: "general"},
                  {question: "How would you feel about working for someone who knows less than you?", category: "general"},
                  {question: "How do you think I rate as an interviewer?", category: "general"},
                  {question: "There's no right or wrong answer, but if you could be anywhere in the world right now, where would you be?", category: "general"},
                  {question: "What's the last book you read?", category: "general"},
                  {question: "What's the best movie you've seen in the last year?", category: "general"},
                  {question: "What would you do if you won the lottery?", category: "general"},
                  {question: "What do you do in your spare time?", category: "general"},
                  {question: "How many times do a clock's hands overlap in a day?", category: "brainteaser"},
                  {question: "How would you weigh a plane without scales?", category: "brainteaser"},
                  {question: "Tell me 10 ways to use a pencil other than writing.", category: "brainteaser"},
                  {question: "Sell me this pencil.", category: "brainteaser"},
                  {question: "Why is there fuzz on a tennis ball?", category: "brainteaser"},
                  {question: "With your eyes closed, tell me step-by-step how to tie my shoes.", category: "brainteaser"},
                ])

